### ISSUE TITLE
Use multipart/form-data for POST requests

### ISSUE THREAD

**Issue by elFua** [bjorns/aem-cmd#25]
This is just a placeholder for re-opening issue [#19](https://github.com/bjorns/aem-cmd/issues/19#issuecomment-260175971) given that `requests` has support for `multipart/form-data` either directly via `requests.post(url, files=payload)` (where `payload` is a tuple rather than a dictionary, so that same field names can be used repeatedly), (also see the [docs](http://docs.python-requests.org/en/latest/user/quickstart/#post-a-multipart-encoded-file)) or via [requests_toolbelt](https://toolbelt.readthedocs.io/en/latest/uploading-data.html). This will allow proper support for typehints.

More details are provided in the [original issue #19](https://github.com/bjorns/aem-cmd/issues/19#issuecomment-260175971).

**Comment by bjorns** [comment]
Implemented for setprop tool
