### ISSUE TITLE
Groovy command has incorrect help text

### ISSUE THREAD

**Issue by daniespr** [bjorns/aem-cmd#27]
I tried to make use of the groovy console to run scripts on a server that run's both an author and publish instance of AEM.

I was able to run the script that I had loaded against the author instance but I was not able to pass a server argument to then target another AEM instance.

Then when I checked the help command I saw the read out : 
```
Usage: acmd groups <list|create|adduser> [options] <groupname> <username>

Options:
  -h, --help  show this help message and exit
  -r, --raw   output raw response data
```

This seems to be copy and pasted from another command, not sure if this is an indication of the full functionality

Please can the help info be corrected for the groovy command

**Comment by bjorns** [comment]
Thanks, I have updated the help text on the latest commit. In order to run against a different server, put the server option before the tool like so:

    $ acmd -s publish groovy myfile.groovy
