### ISSUE TITLE
The ability to pass the host,username and password in the command

### ISSUE THREAD

**Issue by daniespr** [bjorns/aem-cmd#28]
Currently the documentation shows that If you want to store any server configuration i.e host name, username and password, you need to update the **~/.acmd.rc** file.

For security reasons we cannot store our server passwords outside of encrypted files, so we could not make use of this solution to update content.

Could we have an option other than ```--server``` so that we can pass through the ```--host``` ```--username``` and ```--password``` so that we don't have to store the password in a file

**Comment by bjorns** [comment]
There is no support for this at the moment. There are vague plans to support encrypted passwords in .acmd files in a future release.

**Comment by bjorns** [comment]
If you're interested I just pushed a new version 0.14beta that contains basic support for encrypted passwords. I'd love some feedback on functionality and documentation.
